CheckPeriodSec: 60
MachineName: local

EmailConfiguration:
  Host: smtp.gmail.com
  Port: 465
  Email: maxim.markelow@siisltd.ru
  Password: 
  
Emails:
  - max.markelow@gmail.com
  
Drives:
  - DeviceName: C
    ThresholdValue: 150
    TriggerMode: Accuracy
    MeasurementUnit: GB

  - DeviceName: D
    ThresholdValue: 0.8
    TriggerMode: Percentile
    MeasurementUnit: GB